name: condorcet_vote
services:
  php:
    build: ./Docker/Web/.
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # commentez la ligne suivante en production, elle permet d'avoir de beaux logs lisibles en dev
    tty: true
    networks:
      - condorcet-network
    depends_on:
      - mariadb
    environment:
      - CONDORCETDB_USER_PASSWORD=${CONDORCETDB_USER_PASSWORD}
      - CADDY_EXTRA_CONFIG=${CADDY_EXTRA_CONFIG}

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=100M
    depends_on:
      - mariadb
    networks:
      - condorcet-network
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - condorcetdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CONDORCETDB_ROOT_PASSWORD}
      - MYSQL_USER=condorcet_user
      - MYSQL_PASSWORD=${CONDORCETDB_USER_PASSWORD}
      - MYSQL_DATABASE=condorcet
    #ports:
      #- 3306:3306
    networks:
      - condorcet-network

networks:
  condorcet-network: {}

volumes:
  condorcetdb:
    external: true
  caddy_data:
  caddy_config: